### PR TITLE
Fix: authentication middleware

### PR DESCRIPTION
**Pull request by geofrocker**
I am using the boilerplate to guide my folder and file structure for a nodejs,express and mongodb rest api .I realised that if app.use() is placed before app.all(), the middleware is not called because the routes have already been used hence fixing it that way and now it works.  Besides that, this tutorial has been of match help. Hope u see this.

### CODE REVIEW

**Comment by geofrocker** [comment]
@aichbauer

**Comment by aichbauer** [comment]
@geofrocker thanks for your contribution.

you are right I just tested it and this is definitely something which should be fixed.

do you think its better to have the middleware directly in the `app.use` function?

```js
app.use('/private', (req, res, next) => auth(req, res, next), mappedAuthRoutes);
```

**Comment by geofrocker** [comment]
The I really think its a nice idea because it keeps the code dry

**Comment by aichbauer** [comment]
@geofrocker okay, would you mind changing it in your PR? Then we can merge this PR.

**Comment by geofrocker** [comment]
I think it should keep this way. I dont see why we should actually change it. `app.use('/private', (req, res, next) => auth(req, res, next), mappedAuthRoutes);`

**Pull request merged**
