### PR TITLE
Default to JWT_SECRET if available

### PR DESCRIPTION
**Pull request by snyff**
This change will make JWT_SECRET the default if available regardless of the environment.

### CODE REVIEW

**Comment by aichbauer** [comment]
Thank you for your contribution.

I will take a look into the PR tomorrow.

**Comment by aichbauer** [comment]
Sorry for the long wait.

I want your opinion, because actually you let me see that this service is not working properly, as a secret should always be there in production and also this secret should be safe. We should also let the user know if they use a unsafe JWT_SECRET when they are not using `production`. `jsonwebtoken` uses `HS256` as algorithmen, I read an [article](https://auth0.com/blog/brute-forcing-hs256-is-possible-the-importance-of-using-strong-keys-to-sign-jwts/) that it is possible to actually brute force the secret of a HS256 algorithm when using a "bad" secret. Actually one should use a 256 bit secret. which is the equivalent of 32 charcaters, since 1 char is 8 bit.

wouldn't it better to actually throw when using `NODE_ENV=production`. Right now a user of this app wouldn't even realise that the secret is `undefined`. Also it would be good to let the user know if they are using a "good" secret.

I would recommend something similar to:

```js
// api/services/production.service.js
const productionService = () => {
  if (
    process.env.NODE_ENV
    // we have to choose a strong secret
    && process.env.JWT_SECRET
    && process.env.DB_NAME
    && process.env.DB_USER
    && process.env.DB_USER
    && process.env.DB_PASS
  ) {
    if (process.env.JWT_SECRET.length <= 31) {
      throw new Error('Not safe for production: JWT_SECRET should be at least 256 bit, e.g. 32 characters long');
    }

    return true;
  }

  throw new Error('Not safe for production: you forgot to set one or more environment variables');
};

module.exports = productionService;
````
  
```js
// api/services/auth.service.js
const jwt = require('jsonwebtoken');

const productionService = require('./production.service');

const safeSecret = process.env.JWT_SECRET ? process.env.JWT_SECRET.length >= 32 : true;

const secret = () => {
  if (
    safeSecret
    || (
      process.env.NODE_ENV === 'production'
      && productionService()
    )
  ) {
    return process.env.JWT_SECRET;
  }

  if(!safeSecret) {
    console.error('\n\n\nYou are using a JWT_SECRET that would not be safe for production. Keep in mind that your secret should be at least 256 bit, e.g. 32 characters long.\n\n\n')
    return process.env.JWT_SECRET;
  }

  return 'secret';
};

const mySecret = secret();

const authService = () => {
  const issue = (payload) => jwt.sign(payload, mySecret, { expiresIn: 10800 });
  const verify = (token, cb) => jwt.verify(token, mySecret, {}, cb);

  return {
    issue,
    verify,
  };
};

module.exports = authService;
```

So  @snyff what do you think of that?

**Comment by snyff** [comment]
Hi @aichbauer,

I looked into it before providing the PR. jsonwebtoken will actually throw an exception if the secret is undefined. However, as you said, enforcing a strong secret is definitely a good idea :)

**Comment by aichbauer** [comment]
thanks @snyff I did not know that.

I think we should provide something like that, because this function is not called on `yarn start` so the system would break on the first issued token. If you run that in a docker container wich restarts on failure you can not use the program and may not notice whats the problem.

Would you mind update the PR?

**Comment by aichbauer** [comment]
@snyff any update?

**Comment by snyff** [comment]
Hi @aichbauer,

Sorry, I completely forgot about this. I may get back to it once I come back from leave in a few weeks. 

Louis

**Comment by aichbauer** [comment]
closed due to no response, but this will be added soon since it is a good addition....

**Pull request closed without merging**
